"""Compliance reminders — per-entity recurring tax / regulatory filings.

Phase 8 of approved roadmap. Solves "did we file GSTR-3B for last
month?" "when's the next PF deposit due?" "the CA needs to remind us
about ROC". 5 entities × 8 filing types = 40+ moving parts that the
team currently tracks in WhatsApp and email.

Three tables:

- ``compliance_obligations``  — the TEMPLATE / config row. One per
                                (company, kind). Carries cadence
                                (monthly / quarterly / half_yearly /
                                yearly), due_day, assigned owner
                                (e.g. the CA from Contacts), and the
                                reminder lead time.
- ``compliance_occurrences``  — concrete instances generated by the
                                scheduler. Each has period_label
                                ("Jun 2026" / "Q1 FY26-27"), due_date,
                                status (pending / filed / skipped /
                                overdue), filed metadata.
- ``compliance_reminders``    — dedup row keyed on
                                (occurrence_id, kind) where kind is
                                'T_N' / 'T_3' / 'T_0' / 'overdue'.

The scheduler (added in app/scheduler.py) runs daily to:
1. Generate occurrences for the next 120 days from every active
   obligation, ON CONFLICT DO NOTHING via (obligation_id, due_date).
2. Fire reminders for each pending occurrence whose due_date falls
   inside the appropriate window. Each kind fires at most once.

Authz lives in the router. Manage roles: super_admin, founder,
founder_office_coordinator, founder_office_support, hr_admin. Same
set as Vendors + Assets — keeps the ops surface coherent.

Revision ID: 0026_compliance
Revises: 0025_vendors
Create Date: 2026-06-17
"""
from alembic import op


revision = "0026_compliance"
down_revision = "0025_vendors"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS public.compliance_obligations (
            id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
            company_id           uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
            -- Logical kind. Free text so HR can add anything; common
            -- values surfaced in the UI:
            --   gstr_3b, gstr_1, tds_payment, tds_return,
            --   pf, esi, pt_employee, pt_employer, roc_annual,
            --   income_tax_return, advance_tax, professional_tax, other
            kind                 text NOT NULL,
            -- Human-friendly title (e.g. "GSTR-3B monthly filing").
            name                 text NOT NULL,
            -- monthly | quarterly | half_yearly | yearly
            cadence              text NOT NULL DEFAULT 'monthly',
            -- Day of due-month (1-31). For monthly: due_day of
            -- (period_month + 1). For quarterly / yearly: due_day of
            -- the configured due month (see due_month_offset below).
            due_day              int NOT NULL DEFAULT 20 CHECK (due_day BETWEEN 1 AND 31),
            -- Months added to the period END to get the due month.
            -- Example: GSTR-3B for June (period_end = Jun 30) is due
            -- Jul 20 → offset = 1, due_day = 20.
            due_month_offset     int NOT NULL DEFAULT 1 CHECK (due_month_offset BETWEEN 0 AND 12),
            -- Owner — gets the notifications + emails. Usually the CA
            -- on the team, set via the Contacts module today; this is
            -- just a profiles.id so any internal user works too.
            assigned_to_user_id  uuid REFERENCES public.profiles(id),
            -- Optional descriptive contact id from the Contacts
            -- module (CA / CS firm reference). Not load-bearing for
            -- reminders today — set for human reference.
            assigned_contact_id  uuid REFERENCES public.contacts(id),
            reminder_days_before int NOT NULL DEFAULT 7 CHECK (reminder_days_before BETWEEN 0 AND 60),
            is_active            boolean NOT NULL DEFAULT true,
            notes                text,
            created_at           timestamptz NOT NULL DEFAULT now(),
            created_by           uuid REFERENCES public.profiles(id),
            updated_at           timestamptz NOT NULL DEFAULT now(),
            updated_by           uuid REFERENCES public.profiles(id)
        );
        CREATE INDEX IF NOT EXISTS idx_compliance_obligations_company ON public.compliance_obligations(company_id);
        CREATE INDEX IF NOT EXISTS idx_compliance_obligations_active  ON public.compliance_obligations(is_active);

        CREATE TABLE IF NOT EXISTS public.compliance_occurrences (
            id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
            obligation_id  uuid NOT NULL REFERENCES public.compliance_obligations(id) ON DELETE CASCADE,
            period_label   text NOT NULL,
            period_start   date NOT NULL,
            period_end     date NOT NULL,
            due_date       date NOT NULL,
            -- pending | filed | skipped | overdue
            -- "overdue" is just a UI hint based on due_date < today
            -- AND status='pending'. Stored as 'pending' until filed.
            status         text NOT NULL DEFAULT 'pending',
            filed_at       timestamptz,
            filed_by       uuid REFERENCES public.profiles(id),
            reference      text,
            amount         numeric(14,2),
            notes          text,
            created_at     timestamptz NOT NULL DEFAULT now(),
            UNIQUE (obligation_id, due_date)
        );
        CREATE INDEX IF NOT EXISTS idx_compliance_occurrences_due
            ON public.compliance_occurrences(due_date) WHERE status = 'pending';
        CREATE INDEX IF NOT EXISTS idx_compliance_occurrences_obligation
            ON public.compliance_occurrences(obligation_id, due_date DESC);

        CREATE TABLE IF NOT EXISTS public.compliance_reminders (
            occurrence_id uuid NOT NULL REFERENCES public.compliance_occurrences(id) ON DELETE CASCADE,
            kind          text NOT NULL,   -- 'T_N' | 'T_3' | 'T_0' | 'overdue'
            sent_at       timestamptz NOT NULL DEFAULT now(),
            PRIMARY KEY (occurrence_id, kind)
        );
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DROP TABLE IF EXISTS public.compliance_reminders;
        DROP TABLE IF EXISTS public.compliance_occurrences;
        DROP TABLE IF EXISTS public.compliance_obligations;
        """
    )
